const params=new URLSearchParams(location.search);const room=(params.get('room')||'rmmla2026').replace(/[^a-zA-Z0-9_-]/g,'')||'rmmla2026';const presenter=location.pathname.includes('presenter')||params.get('mode')==='present';if(presenter)document.body.classList.add('presenter');
for(const el of document.querySelectorAll('[data-img]')){const key=el.dataset.img;if(window.V12_IMAGES?.[key])el.style.backgroundImage=`url("${window.V12_IMAGES[key]}")`}
const screens=[...document.querySelectorAll('.screen')],prog=document.querySelector('.progress'),notes=document.getElementById('notes');let current=0,contrib=[],poemMode='read',poemCount=3,poemPage=0,loopTimer=null,loopOn=false;
screens.forEach((s,i)=>{const a=document.createElement('a');a.href='#'+s.id;a.title=s.id;a.onclick=()=>setCurrent(i);prog.appendChild(a)});const dots=[...prog.children];
function setCurrent(i){current=Math.max(0,Math.min(screens.length-1,i));dots.forEach((d,j)=>d.classList.toggle('active',j===current));notes.textContent=screens[current].dataset.note||'';if(screens[current].id==='poem')startPoemView()}
function go(i){const n=Math.max(0,Math.min(screens.length-1,i));screens[n].scrollIntoView({behavior:matchMedia('(prefers-reduced-motion:reduce)').matches?'auto':'smooth'});setCurrent(n)}
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>.55)setCurrent(screens.indexOf(e.target))}),{threshold:[.55]});screens.forEach(s=>obs.observe(s));setCurrent(0);
document.getElementById('prev').onclick=()=>go(current-1);document.getElementById('next').onclick=()=>go(current+1);document.getElementById('notesBtn').onclick=()=>document.body.classList.toggle('notes-on');
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement.tagName))return;if(e.key==='ArrowRight'||e.key==='PageDown'||e.key===' '){e.preventDefault();go(current+1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();go(current-1)}if(e.key.toLowerCase()==='p')document.body.classList.toggle('notes-on');if(e.key.toLowerCase()==='l')toggleLoop()});
const prompts={between:'I have been between',asked:'Graduate school asked me to be',also:'But I was also',interrupted:'Something interrupted my route:',called:'Something kept calling me back:',notyet:'I do not know yet',made:'Someone made room for me by',little:'A little movement that mattered was',possible:'What would make this possible:',becoming:'I am still becoming'};
function renderRoute(){const z=document.getElementById('route-frags');z.innerHTML='';const arr=contrib.slice(-8);const slots=[[5,8],[22,68],[37,14],[52,66],[65,10],[76,62],[14,38],[58,38]];arr.forEach((x,i)=>{const d=document.createElement('div');d.className='route-frag';d.textContent=x.text;d.style.left=slots[i][0]+'%';d.style.top=slots[i][1]+'%';d.style.setProperty('--r',(-5+i%3*4)+'deg');z.appendChild(d)})}
function poemLines(arr){const stage=document.getElementById('poem-stage');stage.innerHTML='';if(!arr.length){stage.innerHTML='<div class="poem-empty">waiting for approved audience fragments…</div>';return}arr.forEach(x=>{const p=document.createElement('div');p.className='poem-line';const lead=prompts[x.type]||'';p.innerHTML=`<span class="lead">${esc(lead)}</span> ${esc(x.text)}`;stage.appendChild(p)})}
function esc(s){return String(s).replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]||m))}
function ordered(seed=1){return [...contrib].sort((a,b)=>Math.sin(hash(a.id)+seed)-Math.sin(hash(b.id)+seed))}function hash(s){let h=0;for(const c of s)h=(h*31+c.charCodeAt(0))>>>0;return h}
function renderPoem(){const status=document.getElementById('poem-status');if(!contrib.length){poemLines([]);status.textContent='';return}if(poemMode==='accumulate'){poemCount=Math.min(poemCount,contrib.length);poemLines(contrib.slice(0,poemCount));status.textContent=`accumulating · ${poemCount} of ${contrib.length}`}else{const per=6,pages=Math.max(1,Math.ceil(contrib.length/per)),page=((poemPage%pages)+pages)%pages,arr=(poemMode==='arrange'?ordered(page+2):contrib).slice(page*per,page*per+per);poemLines(arr);status.textContent=pages>1?`${poemMode} · movement ${page+1} of ${pages}`:poemMode}}
function startPoemView(){if(poemMode==='accumulate')renderPoem();else{poemMode='read';renderPoem()}}
document.getElementById('accBtn').onclick=()=>{poemMode='accumulate';poemCount=Math.min(contrib.length,Math.max(1,poemCount+1));renderPoem()};document.getElementById('arrangeBtn').onclick=()=>{poemMode='arrange';poemPage=(poemPage+1)%Math.max(1,Math.ceil(contrib.length/6));renderPoem()};document.getElementById('readBtn').onclick=()=>{poemMode='read';renderPoem()};document.getElementById('loopBtn').onclick=toggleLoop;
function toggleLoop(){loopOn=!loopOn;document.getElementById('loopBtn').textContent=loopOn?'stop loop':'loop';clearInterval(loopTimer);if(loopOn){poemMode='arrange';loopTimer=setInterval(()=>{if(current!==screens.findIndex(s=>s.id==='poem'))go(screens.findIndex(s=>s.id==='poem'));poemPage++;renderPoem()},15000)}}
async function load(){try{const r=await fetch('/api/contributions?room='+encodeURIComponent(room),{cache:'no-store'});if(r.ok){contrib=await r.json();renderRoute();renderPoem()}}catch{}}
function stream(){try{const e=new EventSource('/api/stream?room='+encodeURIComponent(room));e.onmessage=ev=>{try{const m=JSON.parse(ev.data);if(m.type==='snapshot')contrib=m.items;if(m.type==='add'&&!contrib.some(x=>x.id===m.item.id))contrib.push(m.item);if(m.type==='remove')contrib=contrib.filter(x=>x.id!==m.id);renderRoute();renderPoem()}catch{}}}catch{}}
load();stream();
