#!/usr/bin/env node
'use strict';
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const ROOT=__dirname,DATA_DIR=process.env.DATA_DIR?path.resolve(process.env.DATA_DIR):path.join(ROOT,'data'),DATA_FILE=process.env.DATA_FILE?path.resolve(process.env.DATA_FILE):path.join(DATA_DIR,'poems.json');
const PORT=Number(process.env.PORT||8080),HOST=process.env.HOST||'0.0.0.0',ADMIN_TOKEN=process.env.ADMIN_TOKEN||'',MAX_PER_ROOM=900,MAX_TEXT=320;
const VALID_TYPES=new Set(['between','asked','also','interrupted','called','notyet','made','little','possible','becoming','carry','free','grad_thoughts','grad_shape','imagined','daemon_return','conduct_form']);
const clients=new Map();fs.mkdirSync(DATA_DIR,{recursive:true});let db={};try{db=JSON.parse(fs.readFileSync(DATA_FILE,'utf8'))}catch{db={}}
function safeRoom(raw='rmmla2026'){const r=String(raw||'').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,40);return r||'rmmla2026'}
function save(){const tmp=DATA_FILE+'.tmp';fs.writeFileSync(tmp,JSON.stringify(db,null,2));fs.renameSync(tmp,DATA_FILE)}
function json(res,code,obj){const body=JSON.stringify(obj);res.writeHead(code,{'Content-Type':'application/json; charset=utf-8','Content-Length':Buffer.byteLength(body),'Cache-Control':'no-store'});res.end(body)}
function readBody(req,limit=16384){return new Promise((resolve,reject)=>{let data='';req.on('data',c=>{data+=c;if(data.length>limit){reject(new Error('too large'));req.destroy()}});req.on('end',()=>resolve(data));req.on('error',reject)})}
function broadcast(room,payload){const set=clients.get(room);if(!set)return;const msg=`data: ${JSON.stringify(payload)}\n\n`;for(const r of set){try{r.write(msg)}catch{}}}
function mime(file){const e=path.extname(file).toLowerCase();return ({'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.json':'application/json; charset=utf-8','.jpg':'image/jpeg','.jpeg':'image/jpeg','.png':'image/png','.svg':'image/svg+xml','.txt':'text/plain; charset=utf-8'})[e]||'application/octet-stream'}
function cache(file){return path.extname(file)==='.html'?'no-cache':'public, max-age=3600'}
function serveFile(res,pathname){let rel=pathname.replace(/^\/+/,'');if(!rel)rel='index_v16.html';const aliases={audience:'index_v16.html','audience.html':'index_v16.html',contribute:'contribute_v16.html','contribute.html':'contribute_v16.html',c:'contribute_v16.html','respond-state':'respond_state_v13.html','respond-state.html':'respond_state_v13.html',q2:'respond_state_v13.html','respond-imagined':'respond_imagined_v13.html','respond-imagined.html':'respond_imagined_v13.html',q5:'respond_imagined_v13.html',presentation:'presentation_v16.html','presentation.html':'presentation_v16.html',p:'presentation_v16.html',presenter:'presentation_v16.html','presenter.html':'presentation_v16.html',explore:'explore_v12.html','explore.html':'explore_v12.html',x:'explore_v12.html',moderator:'moderator_v16.html','moderator.html':'moderator_v16.html',links:'links_v16.html','links.html':'links_v16.html'};if(aliases[rel])rel=aliases[rel];const file=path.resolve(ROOT,rel);if(!file.startsWith(ROOT+path.sep)){res.writeHead(403);return res.end('Forbidden')}fs.stat(file,(err,st)=>{if(err||!st.isFile()){res.writeHead(404,{'Content-Type':'text/plain; charset=utf-8'});return res.end('Not found')}res.writeHead(200,{'Content-Type':mime(file),'Cache-Control':cache(file)});fs.createReadStream(file).pipe(res)})}
const server=http.createServer(async(req,res)=>{const u=new URL(req.url,`http://${req.headers.host||'localhost'}`),p=u.pathname;
if(p==='/api/status'&&req.method==='GET')return json(res,200,{ok:true,version:16,storage:'server',moderation:!!ADMIN_TOKEN,premoderation:true,poemForms:['accumulate','pantoum','cento','loop']});
if(p==='/api/contributions'&&req.method==='GET'){const room=safeRoom(u.searchParams.get('room'));return json(res,200,(db[room]||[]).filter(x=>!x.hidden))}
if(p==='/api/contributions'&&req.method==='POST'){try{const room=safeRoom(u.searchParams.get('room')),body=JSON.parse(await readBody(req)||'{}'),type=VALID_TYPES.has(body.type)?body.type:'between',text=String(body.text||'').replace(/[\u0000-\u001F\u007F]/g,' ').replace(/\s+/g,' ').trim().slice(0,MAX_TEXT);if(!text)return json(res,400,{error:'empty fragment'});const item={id:crypto.randomUUID(),type,text,createdAt:Date.now(),hidden:true,pending:true};if(!db[room])db[room]=[];db[room].push(item);if(db[room].length>MAX_PER_ROOM)db[room]=db[room].slice(-MAX_PER_ROOM);save();return json(res,201,{...item,status:'pending'})}catch{return json(res,400,{error:'invalid request'})}}
if(p==='/api/stream'&&req.method==='GET'){const room=safeRoom(u.searchParams.get('room'));res.writeHead(200,{'Content-Type':'text/event-stream; charset=utf-8','Cache-Control':'no-cache, no-transform','Connection':'keep-alive','X-Accel-Buffering':'no'});res.write(`data: ${JSON.stringify({type:'snapshot',items:(db[room]||[]).filter(x=>!x.hidden)})}\n\n`);if(!clients.has(room))clients.set(room,new Set());clients.get(room).add(res);const ping=setInterval(()=>{try{res.write(': keepalive\n\n')}catch{}},25000);req.on('close',()=>{clearInterval(ping);clients.get(room)?.delete(res);if(clients.get(room)?.size===0)clients.delete(room)});return}
if(p==='/api/moderation'&&req.method==='GET'){if(!ADMIN_TOKEN||req.headers['x-admin-token']!==ADMIN_TOKEN)return json(res,403,{error:'admin token required'});const room=safeRoom(u.searchParams.get('room'));return json(res,200,db[room]||[])}
if(p==='/api/moderate'&&req.method==='POST'){if(!ADMIN_TOKEN||req.headers['x-admin-token']!==ADMIN_TOKEN)return json(res,403,{error:'admin token required'});try{const room=safeRoom(u.searchParams.get('room')),body=JSON.parse(await readBody(req)||'{}'),item=(db[room]||[]).find(x=>x.id===String(body.id||''));if(!item)return json(res,404,{error:'fragment not found'});item.hidden=!!body.hidden;item.pending=body.pending===undefined?false:!!body.pending;save();broadcast(room,item.hidden?{type:'remove',id:item.id}:{type:'add',item});return json(res,200,{ok:true,...item})}catch{return json(res,400,{error:'invalid request'})}}
if(p==='/api/clear'&&req.method==='POST'){if(!ADMIN_TOKEN||req.headers['x-admin-token']!==ADMIN_TOKEN)return json(res,403,{error:'admin token required'});const room=safeRoom(u.searchParams.get('room'));db[room]=[];save();broadcast(room,{type:'snapshot',items:[]});return json(res,200,{ok:true,room})}
serveFile(res,p)});
server.listen(PORT,HOST,()=>console.log(`In the Between V16 running on ${HOST}:${PORT}`));