(()=>{
const params=new URLSearchParams(location.search);const room=(params.get('room')||'rmmla2026').replace(/[^a-zA-Z0-9_-]/g,'').slice(0,40)||'rmmla2026';
const isPresenter=location.pathname.toLowerCase().includes('presenter')||params.get('mode')==='present';document.body.classList.add(isPresenter?'presenter':'view');
document.querySelectorAll('a[href*="room=rmmla2026"]').forEach(a=>a.href=a.href.replace('room=rmmla2026','room='+encodeURIComponent(room)));if(!isPresenter)document.querySelectorAll('.presenter-only').forEach(x=>x.style.display='none');
const screens=[...document.querySelectorAll('.screen')];let current=0,loopTimer=null,looping=false;const note=document.getElementById('presenter-note');
function setCurrent(i){current=Math.max(0,Math.min(screens.length-1,i));if(note)note.textContent=screens[current]?.dataset.note||''}
function go(i,behavior='smooth'){i=Math.max(0,Math.min(screens.length-1,i));screens[i].scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'auto':behavior});setCurrent(i)}
const obs=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting&&e.intersectionRatio>.55){const i=screens.indexOf(e.target);setCurrent(i);if(e.target.id==='poem'&&isPresenter)setPoemMode('pantoum')}}),{threshold:[.55]});screens.forEach(s=>obs.observe(s));
document.getElementById('prev')?.addEventListener('click',()=>go(current-1));document.getElementById('next')?.addEventListener('click',()=>go(current+1));document.getElementById('notes')?.addEventListener('click',()=>document.body.classList.toggle('notes'));
function stopLoop(){looping=false;if(loopTimer)clearTimeout(loopTimer);loopTimer=null}function startLoop(){looping=true;let idx=current;const tick=()=>{if(!looping)return;idx=(idx+1)%screens.length;go(idx);if(screens[idx].id==='poem')setPoemMode('loop');loopTimer=setTimeout(tick,screens[idx].id==='poem'?20000:9500)};tick()}document.getElementById('loop')?.addEventListener('click',()=>{looping?stopLoop():startLoop()});
document.addEventListener('keydown',e=>{if(['INPUT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight'||e.key==='PageDown'||e.key===' '){e.preventDefault();stopLoop();go(current+1)}if(e.key==='ArrowLeft'||e.key==='PageUp'){e.preventDefault();stopLoop();go(current-1)}if(e.key.toLowerCase()==='p'&&isPresenter)document.body.classList.toggle('notes');if(e.key.toLowerCase()==='l'&&isPresenter){looping?stopLoop():startLoop()}});
let contributions=[];
const leads={between:'I have been between',asked:'Graduate school asked me to be',also:'But I was also',interrupted:'Something interrupted my route:',called:'Something kept calling me back:',notyet:'I do not know yet',made:'Someone made room for me by',little:'A little movement that mattered was',possible:'What would make this possible:',becoming:'I am still becoming',carry:'Something that carries over is',grad_thoughts:'',grad_shape:'',imagined:''};
const lineFor=c=>((leads[c.type]||'')+' '+c.text).replace(/\s+/g,' ').trim();
async function load(){try{const r=await fetch('/api/contributions?room='+encodeURIComponent(room),{cache:'no-store'});if(r.ok){contributions=await r.json();renderRoute();renderPoem()}}catch{}}
function stream(){if(!window.EventSource)return;const es=new EventSource('/api/stream?room='+encodeURIComponent(room));es.onmessage=e=>{try{const m=JSON.parse(e.data);if(m.type==='snapshot')contributions=m.items;else if(m.type==='add'){if(!contributions.some(x=>x.id===m.item.id))contributions.push(m.item)}else if(m.type==='remove')contributions=contributions.filter(x=>x.id!==m.id);renderRoute();renderPoem()}catch{}}}
function renderRoute(){const z=document.querySelector('[data-live="route"]');if(!z)return;z.innerHTML='';const slots=[[6,14],[19,67],[34,12],[49,69],[63,19],[76,64],[82,34],[26,38],[56,45],[8,48]];contributions.slice(-10).forEach((c,i)=>{const d=document.createElement('div');d.className='frag';d.textContent=c.text;d.style.left=slots[i%slots.length][0]+'%';d.style.top=slots[i%slots.length][1]+'%';d.style.setProperty('--r',(-5+(i*7)%10)+'deg');d.style.borderLeftColor=['var(--skin2)','var(--skin3)','var(--skin4)','var(--teal)','var(--graphite)'][i%5];z.appendChild(d)})}
let poemMode='pantoum',poemPage=0,poemTimer=null,accumIndex=0;const centoPageSize=7;
function clearPoemTimer(){if(poemTimer)clearTimeout(poemTimer);poemTimer=null}
function setPoemMode(m){clearPoemTimer();poemMode=m;poemPage=0;if(m==='accumulate')accumIndex=0;renderPoem();if(m==='accumulate')scheduleAccum();if(m==='loop')schedulePoemLoop()}
document.querySelectorAll('[data-poem]').forEach(b=>b.addEventListener('click',()=>setPoemMode(b.dataset.poem)));
function buildPantoum(lines){if(lines.length<6)return null;const first=[lines[0],lines[1],lines[2],lines[3]];const stanzas=[first];let prev=first,cursor=4;while(cursor+1<lines.length){const next=[prev[1],lines[cursor],prev[3],lines[cursor+1]];stanzas.push(next);prev=next;cursor+=2}if(cursor<lines.length){const next=[prev[1],lines[cursor],prev[3],first[2]];stanzas.push(next);prev=next}const close=[prev[1],first[2],prev[3],first[0]];stanzas.push(close);return stanzas}
function renderPantoum(out,prog){const lines=contributions.map(lineFor).filter(Boolean);const stanzas=buildPantoum(lines);if(!stanzas){renderCento(out,prog,true);return}const pages=Math.max(1,Math.ceil(stanzas.length/2));poemPage=((poemPage%pages)+pages)%pages;const group=stanzas.slice(poemPage*2,poemPage*2+2);const wrap=document.createElement('div');wrap.className='pantoum-wrap';group.forEach((stanza,sidx)=>{const box=document.createElement('div');box.className='pantoum-stanza';const absolute=poemPage*2+sidx;stanza.forEach((line,i)=>{const p=document.createElement('div');p.className='pantoum-line'+(absolute>0&&(i===0||i===2)?' echo':'');p.textContent=line;box.appendChild(p)});wrap.appendChild(box)});out.appendChild(wrap);const from=poemPage*2+1,to=Math.min(stanzas.length,poemPage*2+group.length);prog.textContent='pantoum · stanzas '+from+'–'+to+' of '+stanzas.length+' · repeated lines preserve the audience wording exactly'}
function renderCento(out,prog,fallback=false){const lines=contributions.map(lineFor).filter(Boolean);const pages=Math.max(1,Math.ceil(lines.length/centoPageSize));poemPage=((poemPage%pages)+pages)%pages;const wrap=document.createElement('div');wrap.className='cento-lines';lines.slice(poemPage*centoPageSize,poemPage*centoPageSize+centoPageSize).forEach(line=>{const p=document.createElement('div');p.className='poem-line show';p.textContent=line;wrap.appendChild(p)});out.appendChild(wrap);prog.textContent=(fallback?'cento for now · six approved lines are needed to form the live pantoum · ':'cento · ')+(pages>1?'movement '+(poemPage+1)+' of '+pages+' · ':'')+lines.length+' approved line'+(lines.length===1?'':'s')}
function renderPoem(){const out=document.getElementById('poem-lines'),prog=document.getElementById('poem-progress');if(!out)return;if(!contributions.length){out.innerHTML='<div class="poem-empty">Waiting for approved audience fragments…</div>';if(prog)prog.textContent='';return}out.innerHTML='';if(poemMode==='accumulate'){const arr=contributions.slice(0,Math.max(1,accumIndex));arr.slice(-6).forEach(c=>{const p=document.createElement('div');p.className='poem-line show';p.textContent=lineFor(c);out.appendChild(p)});prog.textContent=Math.min(accumIndex,contributions.length)+' / '+contributions.length+' approved fragments';return}if(poemMode==='cento'){renderCento(out,prog,false);return}renderPantoum(out,prog)}
function scheduleAccum(){if(poemMode!=='accumulate')return;if(accumIndex<contributions.length){accumIndex++;renderPoem();poemTimer=setTimeout(scheduleAccum,2200)}else{poemTimer=setTimeout(()=>setPoemMode('pantoum'),3000)}}
function schedulePoemLoop(){if(poemMode!=='loop')return;const lines=contributions.map(lineFor).filter(Boolean),stanzas=buildPantoum(lines);const pages=stanzas?Math.max(1,Math.ceil(stanzas.length/2)):Math.max(1,Math.ceil(lines.length/centoPageSize));poemPage=(poemPage+1)%pages;renderPoem();poemTimer=setTimeout(schedulePoemLoop,15000)}
load();stream();
const hash=location.hash.replace('#','');const hi=screens.findIndex(s=>s.id===hash);if(hi>=0){setCurrent(hi);setTimeout(()=>screens[hi].scrollIntoView({behavior:'auto'}),0)}else setCurrent(0);
setPoemMode(isPresenter?'accumulate':'pantoum');
})();
